### ISSUE TITLE
Открытые лекции преподавателей факультета компьютерных наук, 9 декабря

### ISSUE THREAD

**Issue by leominov** [leominov/it-ekb-events#7]
[Открытые лекции преподавателей факультета компьютерных наук](https://cs.hse.ru/announcements/212332433.html)

* Process Mining: «недостающее звено» между бизнес-моделированием и науками о данных
* Машинное обучение для оптимизации терапии рака в подгруппах

**Где**: ул. Хохрякова, 10, [БЦ «Палладиум»](http://palladium.red-group.ru/), 4 этаж
**Когда**: 9 декабря, 12:00
**Взять с собой**: Паспорт

**Comment by t3mpo** [comment]
Начало мероприятия в 12.00 по местному времени.
